# Generated by Django 3.2 on 2021-05-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0002_auto_20210509_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='about',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('technology', 'Technology'), ('gadgets', 'Gadgets'), ('design', 'Design'), ('development', 'Development'), ('article', 'Article')], default='article', max_length=250),
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
