# Generated by Django 3.2 on 2021-05-27 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0003_auto_20210515_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
    ]
